services:
  db:
    image: postgres:15.1-bullseye
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd

  jaeger:
    image: jaegertracing/all-in-one:1.67.0
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "5775:5775/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "4318:4318"

  redis:
    image: "redis:5.0.5-alpine3.10"
    ports:
      - 6379:6379
