version: "3.7"

volumes:
  postgres_volume:

services:
  postgresql:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: 11189
    ports:
      - 5432:5432 
    volumes:
      - postgres_volume:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080