GET http://localhost:8000/process?line=текст+тут
content-type: application/json

###
GET http://localhost:8000/process?line=текст+там
content-type: application/json

### 
GET http://localhost:8000/metrics
content-type: application/json


###
GET http://localhost:8000/panic
content-type: application/json

### error
GET http://localhost:8000/error
content-type: application/json


###
GET http://localhost:8000/users
content-type: application/json

### Get user by id 
GET http://localhost:8000/users/b29f95a2-499a-4079-97f5-ff55c3854fcb
content-type: application/json

### Get user by bad id 
GET http://localhost:8000/users/b29f95a2-499a-407800000
content-type: application/json

### Get user by bad id 
GET http://localhost:8000/users/b29f95a2-499a-4079-97f5-ff55c3854fee
content-type: application/json