GET http://localhost:9000/process?line=текст+тweqweqweqweqwт
content-type: application/json

###
GET http://localhost:9000/process?line=текст+там
content-type: application/json

###
GET http://localhost:9000/users

### 
GET http://localhost:9000/panic

### 
GET http://localhost:9000/metrics
content-type: application/json